### ISSUE TITLE
[url rewriting.xml] Documentation missing for <error-handler>

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#105]
As noted in a thread on exist-open http://markmail.org/message/y4jjzyspepkjbxgy, the URL rewriting documentation does not explain the use of `<error-handler>`.

Live site: http://exist-db.org/exist/apps/doc/urlrewrite.xml
GitHub source: https://github.com/eXist-db/documentation/blob/master/data/urlrewrite.xml

**Comment by eriksiegel** [comment]
IMHO the URL rewriting document must be rewritten *completely*. Once I've done all base editorial work on the documentation I will add an issue to request such a rewrite (which I might pickup myself...)

**Comment by duncdrum** [comment]
assigning Wolfgang so this doesn't get lost in the rewrite here #227
