### ISSUE TITLE
[production_web_proxying.xml][production_good_practice.xml] Add instructions for disabling _query and _xupdate parameters

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#109]
Now that https://github.com/eXist-db/exist/pull/1419 has been merged, we need to document how to disable the `_query` and `_xupdate` query parameters via the `xquery-submission` and `xupdate-submission` parameters in `webapp/WEB-INF/web.xml.tmpl`. Candidate destinations for this information would be https://github.com/eXist-db/documentation/blob/master/data/production_web_proxying.xml and https://github.com/eXist-db/documentation/blob/master/data/production_good_practice.xml.

**Comment by duncdrum** [comment]
related to #98 ?

**Comment by adamretter** [comment]
@duncdrum Yes related, but not a duplicate.
