### ISSUE TITLE
[Question] contributions and deletions

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#115]
I seem to remember from the notes of a conference call that the devs would like more help with keeping the documentation up to date. I think that folks are rightfully hesitant to outright delete outdated sections or files from the documentation. This is further compounded by the fact that there are no clear instructions for contributors for how to proceed. Maybe it would help if the repo had: 
1)    a contribution.md outlining the general strategy
2)   a depreciated folder

The folder wouldn't be an ideal solution, but it might be a good stop gap. It could be simply kept around as archive, or cleaned up by the core team as they see fit. It seems much easier to move stuff around, then to create a PR with lots of deletions. Thoughts? I'd be happy to have a go at the contribution.md if it would help.

**Comment by joewiz** [comment]
@duncdrum I think this is a great idea.
