### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/documentation#119]
I can browse documentation, but the search option does not work. Search result for any term is `Found 0 results.` Online version works fine.

**Comment by dizzzz** [comment]
Please could you provide exist-db version ? documentation version?

**Comment by miljanuscumlic** [comment]
It is the latest exist-db release 3.4.0. Documentation version is 0.4.8 I believe: exist/apps/doc/build/doc-0.4.8/documentation.xml

**Comment by duncdrum** [comment]
Just tested with exist 3.5.1 and docs 0.5.0. Search works fine. If this is still a problem, please open a new issue.
