### ISSUE TITLE
devguide_log4j.xml logging documentation

### ISSUE THREAD

**Issue by christianforster** [eXist-db/documentation#12]
http://exist-db.org/exist/apps/doc/devguide_log4j.xml

The term "XXXXXXXXX" is used several times, I suppose it should be replaced with "eXist-db".

**Comment by duncdrum** [comment]
``XXXXXXXXX`` is still there, I would add:
*   the default location of the log files 
to Dannes' list.

**Comment by eriksiegel** [comment]
xxxxxxxx is no more on this page...
