### ISSUE TITLE
Clarify Upgrade guide

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/documentation#120]
I am quoting the General information paragraph from the Upgrade guide on /exist/apps/doc/build/doc-0.4.8/upgrading.xml

> General Information

>Never install a new version of eXist-db into the same directory as an older version:
> 1. Create a backup of your data. If the new version is binary compatible with the old version, keep the data directory (by default in webapp/WEB-INF/data) of the old version. Note: A running instance of eXist-db needs to be stopped before copying files from the data dir.
> 2. Install the new version into a different location.
> 3. If the new version is binary compatible, replace the data directory of the new install with the one from the old one.
> Otherwise you need to do a full restore of the data.

As to a new user this upgrade guide paragraph is not clear enough, at least not on the first reading.

First of all, is it safe to retain old data directory and during the new install just to point the location of the data directory to the old one? I tried it and it seems that this procedure is OK, although doing this [exception is raised](https://github.com/eXist-db/exist/issues/1493). If this is safe to do, it would be nice to state it in this guide (and to take care of that exception).

Regarding aforementioned quote, if it is not safe to point to old data directory, than it should be pointed to a new one. In step 1 copying of files is mentioned and I don't get it why. The old directory is retained and not deleted during second installation. Maybe to move the data that way emptying the old data directory, and later bring all data back by copying to it.

In step 3 it states that I should replace the data directory. Does it mean to replace the contents of the directory, or to make changes in conf.xml to point to another location? What is safe? Maybe both?

**Comment by joewiz** [comment]
@wolfgangmm @adamretter @duncdrum This feedback may be useful in the review of the upgrade guide we discussed in yesterday's Community Call.
