### ISSUE TITLE
[configuration.xml] Update Application Server Configuration page

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/documentation#123]
Application Server Configuration page at exist/apps/doc/build/doc-0.4.8/configuration.xml should be updated. Well, it would be nice.
- The contents are broken and not complete.
-  Paragraph **eXist-db Configuration: Editing conf.xml** states that there are four sections, but there are more.
- Some elements should be updated, e.g. I believe there is no <default-permissions> element under <db-connection> in the conf file.
- It would be helpful to better emphasize headings that represent xml elements so they could be more noticeable in the document
- etc.

**Comment by duncdrum** [comment]
@miljanuscumlic thanks for the report I added a full list of elements to the beginning of the article. Fixing the display of the docbook titles as html headings will have to wait for after a more thorough review of the docbook structure has been completed.
