### ISSUE TITLE
switch to highlight.js for code highlighting

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#141]
see the related issues [here](https://gitlab.exist-db.org/tei-publisher/tei-publisher-app/issues/102) and [here](https://github.com/eXist-db/shared-resources/issues/26)
the current code highlighter is ancient and preventing updates to jquery. Switching to an external [js library](https://highlightjs.org) for code-highlighting should help us in the long-run.

**Comment by adamretter** [comment]
@duncdrum Do you want to add some of these to the community call agenda, so that they get the attention they deserve?

**Comment by duncdrum** [comment]
I have updated the highlight.js xquery parsers. It works within my test build of the documentation app, and passes their tests. However, their Travis is complaining so we ll see how that goes. 
Once, this PR isagalaev/highlight.js#1649 is accepted, we should upgrade in various apps

**Comment by duncdrum** [comment]
![screenshot 2017-11-24 18 25 29](https://user-images.githubusercontent.com/6205362/33219892-2e63cf94-d145-11e7-8ee0-674f33e9bb64.png)

**Comment by duncdrum** [comment]
more samples from tuning.xml
![screenshot 2017-12-15 21 24 37](https://user-images.githubusercontent.com/6205362/34059277-9ff40fda-e1de-11e7-853b-12a7ca32f965.png)
direct xml markup is not properly capture, so is computed constructor syntax, still a few corner cases remain
