### ISSUE TITLE
wishlist of maven tweaks

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#151]
While working on documenting the release procedure, I played with different maven plugins, with varying rates of success. So here is a wishlist of maven features for discussion. Maybe somebody more familiar with the maven way of doing things will be more successful in making them work.

- [ ]  the changes plugin report, should go straight into the desired locations in xar-assembly, and the github release, as `completionGoal` of the `release:prepare` phase
- [x]   Additionally, if we were to start using github milestones this would enable some [neat features](https://maven.apache.org/plugins/maven-changes-plugin/github-report-mojo.html) with this plugin as is
- [ ]   the readme.md should be processed from `src` -> `project-dir` to automatically updated `exist.version` and `project.version.` I couldn't get this to work, for more then one iteration though. 
- [ ]   the default release plugin (despite its descriptions) is really [not very well attuned to github](https://www.atlassian.com/blog/software-teams/maven-git-flow-plugin-for-better-releases). It creates two release tags under normal error free operations, but doesn't actually release a release. (on github releasing a release ≠ tagging a release ≠ creating a release tag). We should consider, if eg. [Maven JGitFlow Plugin](https://bitbucket.org/atlassian/jgit-flow) isn't  better suited to what we want to do. 
- [ ]  The manual `git commit & push` step should be part of `mvn release`, however because the way that release-plugin works this is more likely to cause maven to crash then not to, s.a.
- [ ]   we have two locations the final .xar needs to go exist-db.orgs package repo, and as binary upload  to the github release. In ant there was an upload task for the app repo, we should see if we cannot carry that code over. As for github s.a.
- [ ]   Automated deployment on exist-db.org seems theoretically possible right now, but not very practical, still we shouldn't loose sight of it. 
- [x]   We need to makes sure that folks can build the documentation app on windows systems

**Comment by adamretter** [comment]
@duncdrum This fixes the  Windows build issues - https://github.com/claudius108/kuberam-expath-plugin/pull/4

**Comment by duncdrum** [comment]
there are some known issues with different version of gpg (esp > 2.0) and the way that `maven-release-plugin` and `maven-gpg-plugin` interact.  if we stuck with the release plugin we need to tweak the `pom.xml` to make this more robust.
e.g. with `gpg (GnuPG) 2.2.4` on macOS 10.13.2 i only see a prompt for my passphrase, if i restart gpg-agent before doing a dry-run. `mvn release:prepare` still fails, not matter what i do.

**Comment by duncdrum** [comment]
i ll never learn to like the release plugin but most of the tweaks are in, so closing
