### ISSUE TITLE
Tag the Documentation app with its version number

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/documentation#157]
I would like to suggest setting some kind of visual version tag to the doc app. For example it could be in a header and it should be changed only when a major eXist-db version comes up. That tag would be in correlation with the new version scheme that is adopted.
For example it can be set next to a logo:

![existdb-3](https://user-images.githubusercontent.com/30440470/33677970-ca4f6200-daba-11e7-9794-8d931e238104.png)
In the app it would look like this:

![exist-header](https://user-images.githubusercontent.com/30440470/33678017-e62b26e4-daba-11e7-931f-72b44ebaed14.jpg)

Or it could be something similar to visually distinguish different versions of the documentation.

**Comment by adamretter** [comment]
I think we could have something more subtle perhaps like:

```
Version: 3.0.1
```

Displayed under the logo. The version number is available in XQuery.

**Comment by duncdrum** [comment]
I like the idea as I'm generally in favour of visual aids.  
I see three option though:
-  change the documentation apps' icon to hint at its major version
-  change the exist-db icon, which should be consistent across apps, so the modified version would maybe have to go into shared-resources
-  use xquery to include a version string on the page template
