### ISSUE TITLE
[lucene.xml, indexing.xml] add info about the ICUFoldingFilter and UCA collation

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#168]
### Where is the problem
New features do not yet occur in the docs `lucene.xml` and `indexing.xml` seem the natural candidates.

### What is the problem
see eXist-db/exist#1686, see eXist-db/exist#1575

### Please provide the following
*   exist-db version: `3.6.1`
*   documentation version: `3.0.0`

**Comment by duncdrum** [comment]
see #83

**Comment by joewiz** [comment]
I addressed this in https://github.com/eXist-db/documentation/issues/204#issuecomment-377307157. Ok to close?

**Comment by duncdrum** [comment]
indeed
