### ISSUE TITLE
maven xml plugin stuck with xsd, but docbook moved to relax

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#169]
### Where is the problem
`xml-maven-plugin` doesn't support relaxNG validation.

### What is the problem
Sticking with XSD is suboptimal since relax is the normative format for docbook 5.0 an up.  So lets find a way to use relaxNG schema validation.

see #151

On a side note: build failures because of validation errors seem pretty drastic

**Comment by adamretter** [comment]
It would be fairly trivial to add RelaxNG support to the `xml-maven-plugin`: https://github.com/mojohaus/xml-maven-plugin/tree/master/src/main/java/org/codehaus/mojo/xml

However, I don't really see an immediate use-case for this.

**Comment by duncdrum** [comment]
Our prayers have been heard 🎉  [relaxng support](https://www.mojohaus.org/xml-maven-plugin/examples/validate-relaxng.html)
