### ISSUE TITLE
[beginners-guide-to-xrx-v4.xml] Check XRX document

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/documentation#174]
Can someone check the beginners-guide-to-xrx-v4.xml document? Go through all the steps and see if everything is still ok?

**Comment by duncdrum** [comment]
I brought this up during the last community call. @joewiz might be in the know?

**Comment by plutext** [comment]
Under "Collections and File Conventions" items 5 & 6 recommend collections called edit and search, off application root.  In contrast, eXide's "new application" creates a modules dir.  Presumably edit and search modules should go in there?

**Comment by plutext** [comment]
As a new user, I spent several hours yesterday on 2 problems in my new app (starting from eXide's "new application").  Here is my experience for what it is worth:

1.  why betterForm wasn't processing my HTML (based on the xforms demo address app).  3 changes I had to make to demo:
      (i) file suffix had to be .xhtml
      (ii) Need data-template-at="content" not data-template-at="container-body" (even though container-body is used in demo)
     (iii) root element needs to be html, not a div

2.  HTTP method GET|PUT is not supported by this URL: resource-error
     (i) turns out my XQuery module wasn't registered (though nothing in the logs said this specifically - could eXide check/alert about this?)
    (ii) eventually I found: restxqex:register-module(xs:anyURI ...

3. Of course, there is no logging from your XQuery module until it is actually running, but it would be useful to highlight the approaches to logging, eg:
   (i) Monex + console:log   : http://localhost:8080/exist/apps/monex/console.html
   (ii) let $log := util:log to webapp/WEB-INF/logs/exist.log

**Comment by joewiz** [comment]
@plutext Thanks for your comments. 

- The conventions described in the article are really XRX-specific. You're right that most other eXist apps follow the convention of placing XQuery library modules (if not also main modules) in the "modules" collection.
- The article was written around XSLTForms, not betterFORM. My revision in #185 sets a request attribute preventing betterFORM from intercepting the XForms element in the response, allowing XSLTForms to work as designed.
- Sounds like you're using RESTXQ, which is great but not covered in this article. For RESTXQ questions, feel free to raise these on exist-open.
- You're right that logging would be a great topic to cover. I haven't done so in the revisions in my PR, but let this serve as a request for an article on logging strategies.

**Comment by joewiz** [comment]
@eriksiegel The article is reviewed and confirmed to work. Thanks for prodding - I caught several things which would've caused people trouble.
