### ISSUE TITLE
[configuration.xml] Services section

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/documentation#175]
In configuration.xml there is a section called "Services". To me it seems to serve no purpose. Is there someone that can:

- Either decide it can be deleted -OR-
- Write some introductory paragraph that explains what it is doing here and why it is of interest to the reader -OR-
- Write me a short mail with this explanation in unpolished prose. I will then rewrite and add it.

**Comment by wolfgangmm** [comment]
I'd say delete it. This section seems to list all kinds of modules and extensions in an unordered way, so it is not very helpful at this point of the documentation.

**Comment by eriksiegel** [comment]
Section removed
