### ISSUE TITLE
[debugger.xml] Unclear instructions 

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/documentation#176]
In debugger.xml:

- Somewhere it states “Download the required jar files”. What jar files?
- The instructions to run the debugger in emacs are unclear. What is meant with the example http://www.example.com/script.xql?XDEBUG_SESSION_START ??? this particular one? Any XQuery script?

**Comment by wolfgangmm** [comment]
I think the `debugger.xml` article should be removed entirely as it was never really usable.

**Comment by eriksiegel** [comment]
Noted. When nobody protests I'll remove it before delivering the new doc contents.

**Comment by eriksiegel** [comment]
The debugger doc is removed from the new documentation set
