### ISSUE TITLE
[deployment.xml] Contradictory information 

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/documentation#177]
The section "Running as a Stand-alone Server"in deployment.xml starts of with contradictory information. Does or doesn't the stand alone config support webdav?

**Comment by duncdrum** [comment]
@dizzzz any ideas about web-dav and standalone?

**Comment by dizzzz** [comment]
I checked: webdav is indeed available in the standalone mode:

https://github.com/eXist-db/exist/blob/develop/tools/jetty/etc/standalone/WEB-INF/web.xml#L87

unfortunately there is also a reference to the old and removed Webdav implementation

https://github.com/eXist-db/exist/blob/develop/tools/jetty/etc/standalone/WEB-INF/web.xml#L120

I will remove that one

**Comment by eriksiegel** [comment]
Documentation updated.
