### ISSUE TITLE
cleanup duplicate image files

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#179]
### Where is the problem
`resources/images/` contains all the old img resources. These can go together with `data/db4-versions/*`

### What is the problem
reminder to myself that this can be cleaned up, the new location is in `data/*/assets/`

### Please provide the following
*   exist-db version: 3.6.1
*   documentation version: 3.1.0-snapshot

**Comment by eriksiegel** [comment]
@duncdrum : I suggest we keep this as is for now and delete all the old stuff from the repo after I've finished. Nobody will look at the old stuff anymore.

**Comment by eriksiegel** [comment]
Old DB4 stuff, including images, is removed after the next PR. This one can be closed.
