### ISSUE TITLE
Change to expath-pkg.xml abbrev breaks inbound links

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#181]
### Where is the problem

https://github.com/eXist-db/documentation/blob/ea57032318fde596d4ad4db82012685bb42fec26/pom.xml#L14

### What is the problem

The generated app's expath-pkg.xml declares the package's `@abbrev` as `exist-documentation`. Apps such as fundocs expect the abbrev for eXist to be `doc`. (See https://github.com/eXist-db/function-documentation/issues/19#issuecomment-365825860.) 

Solutions: (1) Change `artifactId` from `exist-documentation` to `doc`. Or (2) Change references to this app from `{doc}` to `{exist-documentation}`. I prefer the former.

### Please provide the following
*   exist-db version: 4.0.0
*   documentation version: 4.0.0

**Comment by joewiz** [comment]
I believe this same phenomenon explains why the documentation app hasn't been missing from the eXist installer since 3.6.0 despite being declared in https://github.com/eXist-db/exist/blob/develop/installer/apps.properties#L2. The actual contents of the 4.0.0 installer's autodeploy directory:

- 00shared-resources-0.4.2.xar
- dashboard-1.0.0.xar
- eXide-2.4.3.xar
- fundocs-0.9.xar
- markdown-0.6.xar
- monex-0.9.12.xar
- usermanager-0.15.1-prod.xar

(eXist 3.5.1 shipped with doc-0.4.9.xar, the last release of the doc repo before the move to maven.)

**Comment by duncdrum** [comment]
@joewiz I seem to remember that during a community call there was opposition to ship with the docs,  the one on exist-db.org should be the canonical version.  

As for thee `@abbrev` that should have been fixed by using the exist-app-parent,  any idea why this is back @adamretter
