### ISSUE TITLE
Search result should add more weight to new articles over old db4 articles

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#183]
### Where is the problem
The index config weighs all `/data/` contents equally. 

### What is the problem
We can not completely get rid of the old contents yet. But when using the search bar, new articles should be weighted higher than old ones, or otherwise highlighted. 

### Please provide the following
*   exist-db version: 4.0.0
*   documentation version: 4.0.0

**Comment by eriksiegel** [comment]
Old articles are no longer there after the next PR. This one can be closed.
