### ISSUE TITLE
[configuration.xml] missing how-to data from wiki

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#193]
### Where is the problem
The old docs had a broken link, to instructions for switching to xslt 2.0 compliant engine, this information is now missing. 
[/doc/configuration#D3.11.33](http://localhost:8080/exist/apps/doc/configuration#D3.11.33)

see #102 

### Please provide the following
*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by adamretter** [comment]
The default has been XSLT 2.0 (via Saxon) for a very long time now. So this can probably just be removed
