### ISSUE TITLE
[scheduler.xml] Refactor scheduler article

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/documentation#198]
The scheduler documentation article is seriously flawed. What to do and how to do this is unclear.  It mentions job types but doesn't do anything with these definitions. A cron tutorial comes out of nowhere with no reference why you would need it. Lots of information but no attempt to relate it.

I suggest a restructure/rewrite.

*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by duncdrum** [comment]
@joewiz you were the last to change the contents of scheduler.xml. Who would be best to take this on in your view?
