### ISSUE TITLE
[security.xml] Refactor and check security article

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/documentation#199]
The security article needs to be refactored. 
- Things are in an awkward order: Very complicated realm and manager  stuff at the beginning, basic stuff at the end
- A lot of text and images about changing the admin password: Unnecessary.
- The resource permissions description is (?) out of date: No mention of the "sticky bit"
- ACL's are important but it only refs some presentation (which might be out of date?)
- It needs thorough checking by someone (@adamretter ?) to make sure what's there is still ok.

I would suggest splitting this document in:
1.  A document with how security works "out of the box" (permissions, ACL's, etc.)
1. The complicated stuff about security managers, realms, etc.

I did not do much editing on this document because I think it needs refactoring and checking *first* by someone that knows and understands the subject thoroughly.

*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by duncdrum** [comment]
I think that changing the admin pw should figure prominently, as it is one of the first things that users should do when installing exist. That is not to say that we shouldn't be more concise about it.
