### ISSUE TITLE
[url rewriting.xml] URL Rewrite article needs refactoring

### ISSUE THREAD

**Issue by xatapult** [eXist-db/documentation#200]
The URL rewriting article needs refactoring. 

URL rewriting is a very important mechanism in eXist for application building and I think it deserves better. 

Take readers in more slowly, postpone stuff about servlets and MVC patterns and all stuff you don't need for the basic understanding to sections at the end, update text *and examples* to the current conventions in running code from the db and not from the fs, etc.

This is a major job. I know because I wrote the chapter about this in the eXist book that took me several days. 

*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by duncdrum** [comment]
see #105

**Comment by duncdrum** [comment]
@wolfgangmm ping about submitting the rewrite

**Comment by wolfgangmm** [comment]
This indeed requires a complete rewrite and I'm not even done with the introduction yet. So it won't be ready for review and has to be delivered later.
