### ISSUE TITLE
Check webdav article

### ISSUE THREAD

**Issue by xatapult** [eXist-db/documentation#201]
The webdav article must be thoroughly checked. It makes a lot of statements about other products which might or might not be true any more.

It also contains screenshots which are probably no longer current. Anyway:  I suggest removing this kind of detailed "howto" instructions on external tools completely: It gets outdated far too quickly and we have no control over its accuracy.

*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by dizzzz** [comment]
From my perspective, the article looks quite complete still. Yes, in a way, documenting other tools here should make no sense, but without this information, it is very difficult to get the other clients started.... that was at least my rationale to have it written this way.

> note: webDAV is very ugly as each agent behaves different in specific (or corner) cases.

ref: http://exist-db.org/exist/apps/doc/webdav.xml

**Comment by dizzzz** [comment]
on second thought.. the documentation looks outdated. But what should be written here?

**Comment by dizzzz** [comment]
I'd say; remove the documentation for now.

alternatively only this text:

```
Introducing WebDAV
eXist-db ships with a WebDAV interface. WebDAV makes it possible to manage database collections and documents just like directories and files in a file system. You can copy, move, delete, view or edit files with any application supporting the WebDAV protocol, including Windows Explorer, macOS Finder, cadaver, KDE Konqueror, oXygen XML Editor, XML Spy, LibreOffice and many others.

The interface has been implemented with excellent open-source Milton WebDAV API for Java.

In the default configuration the WebDAV server can be accessed via the URLs http://localhost:8080/exist/webdav/db/ and https://localhost:8443/exist/webdav/db/ 
```

```
Compatibility
- eXist's Milton based WebDAV interface does not support HTTP Digest Authentication.
- The size of an XML document is presented as a multiple of 4096 bytes, which is eXist's internal pagesize (see conf.xml). The actual size on an XML document stored in the database can not be determined because the size depends on many factors, e.g. the applied serialization parameters.
- A webdav client / enabled application may or may not work with the webdav server of eXist-db, depending on the quality of the implementation of the client. The server fullfills all requirements of the webdav specification
```

- https://en.wikipedia.org/wiki/WebDAV
- https://tools.ietf.org/html/rfc2518 


```
Serialization
When retrieving an XML document via the WebDAV interface, the default serialization settings as defined in conf.xml are effective. It is possible to define specific for the WebDAV interface custom serialization settings.

Copy the file extensions/webdav/webdav.properties into the $EXIST_HOME directory and uncomment/modify the parameters. Changes in this file requires a restart of eXist-db.
```
```properties
## XML Serialization options for the WevDAV
## The file is read from EXIST_HOME
## Be carefull changing the default values !
indent=no
expand-xincludes=no
process-xsl-pi=no
encoding=UTF-8
omit-xml-declaration=no
 ```
                  
webdav.properties
```

```
Notes
From the community we have received feedback that the WebDAV interface is not fully functional when it is accessed via a reverse proxy and a resource's path is altered (aliased) with it.
```

**Comment by dizzzz** [comment]
@eriksiegel @duncdrum  I in essence removed all client/server version specific information....
