### ISSUE TITLE
Check XQuery article

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/documentation#204]
I refactored the XQuery article to the best of my knowledge but it needs to be checked by someone (@wolfgangmm ?) that really knows the state of the XQuery support in eXIst.

The base problem is that it was written when the XQuery 3 facilities were introduced and mentions a lot of things as being "new" (which they no longer are). I already refactored that but there might be other things added in the last years worth mentioning.

*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by eriksiegel** [comment]
IN the collation part parameters are mentioned but not explained (maybe a reference to somewhere where it is explained suffices?)

**Comment by duncdrum** [comment]
see #168, 
aligning eXist with the 3.1 specs is WIP. I ll bring this to the community call tonight (unless you are planning to join).

**Comment by duncdrum** [comment]
@joewiz ping about submitting the rewrite

**Comment by joewiz** [comment]
@duncdrum @eriksiegel Please see my review at #226. I did update the section on collation to include recently added support for UCA, etc.
