### ISSUE TITLE
page.html cause crash and locked DB

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#216]
### Where is the problem
Because `page.html` contains:
```
<body id="grey-top" class="site:expand-links?base=http://exist-db.org/">
```
which calls siteutils.xql from shared resources.

### What is the problem
using the search function on local installs, can cause crashed instances with
exist-log showing if users haven't locally installed all components referenced by the app (eg. demo, fundocs, etc)
```
2018-03-21 17:47:43,483 [qtp1032819313-93] ERROR (FunError.java [eval]:139) - Not found: (http://exist-db.org/apps/site-utils#NOT_FOUND):Not found 
```
and a locked db too boost. 

The only place the app should contain mentions of `exist-db.org` is in the dropdown menu with the link to the exist-db homepage, imv. 

see #158 

### Please provide the following
*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by dizzzz** [comment]
pretty sure this was fixed recently?

**Comment by duncdrum** [comment]
not really, we fixed clicking on navbar links to navigate to e.g. the demo app, by making sure at build that the demo app is actually called demo. 

We haven't fixed the uri resolution of the page.html template itself, which comes into play when you view search results.

**Comment by dizzzz** [comment]
I was referring to the site-Utils thing

**Comment by duncdrum** [comment]
no more crashes with new search … closing
