### ISSUE TITLE
Search on local install seems broken

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#218]
When installing the docs locally alongside demo, and fundocs for debugging #216. I can no longer perform regular searches.

Just use the search bar, there are always 0 results independent of input. 

@eriksiegel can you confirm that search is working as expected in your local copy?

### Please provide the following
*   exist-db version: `4.0.0`
*   documentation version: `4.0.1-SNAPSHOT`

**Comment by eriksiegel** [comment]
@duncdrum No, it isn't working in my local copy. Always get 0 results.

**Comment by duncdrum** [comment]
ok my first guess is that removing the old db4 articles broke stuff. Search used to work with the new articles see #183, i didn't see any other modifications to the modules code.

**Comment by duncdrum** [comment]
yes so we there are a few instances where we need to adapt the xquery code to the new article structure, and change the lucene configuration

also listing25 of lucene.xml should be updated once the changes are made and search is functional again.
