### ISSUE TITLE
[deployment.xml] Deploying eXist-db in a Servlet Container

### ISSUE THREAD

**Issue by nsincaglia** [eXist-db/documentation#221]
Where is the problem
/apps/doc/deployment.xml
Deploying eXist-db in a Servlet Container
The standard distribution does by default launch eXist-db as a web application deployed in a servlet container (if you start eXist via bin/startup.sh or bin\startup.bat). The container used is Jetty.

The Jetty configuration can be found in tools/jetty/webapps/exist-webapp-context.xml. It defines a single web application context value /exist, mapped to the webapp directory. This value can be set to either /exist or /.

What is the problem
In "Deploying eXist-db in a Servlet Container" section, it talks about configuring jetty with $EXIST_HOME/tools/jetty/webapps/exist-webapp-context.xml where the contextPath can be set to /exist or /. There is no mention of also needing to update jetty-web.xml in $EXIST_HOME/tools/jetty/webapps/portal/WEB-INF/ so that the contextPath of the portal does not conflict with the contextPath of one's exist settings. By default, the contextPath settings in $EXIST_HOME/tools/jetty/webapps/portal/WEB-INF/jetty-web.xml are set to '/' and the contextPath settings in $EXIST_HOME/tools/jetty/webapps/exist-webapp-context.xml are set to '/exist'. If you want to change the settings in either file, you need to make sure they are not the same.

Please provide the following
exist-db version: 4.0.0
documentation version: 4.0.0

**Comment by duncdrum** [comment]
I think there might still be a need to modify a `jetty-web.xml ` file, but the context has changed quite a bit from 4.0.0 @nsincaglia is this good to close for 5.2.0 or could you create a PR adding missing info
