### ISSUE TITLE
[devguide_xmlrpc.xml] User-methods have been renamed to Account a long time ago

### ISSUE THREAD

**Issue by burki** [eXist-db/documentation#229]
### What is the problem
User-methods have been renamed to Account a long time ago: https://sourceforge.net/p/exist/mailman/message/26000604/

So the documentation should be changed
* Vector getUsers() -> Vector getAccount()
* Hashtable getUser(String name) -> Hashtable getAccount(String name)
* boolean removeUser(String name) -> boolean removeAccount(String name)
* Instead of setUser, there is now addAccount and updateAccount

### Please provide the following
*   exist-db version: `4.0.0`
*   documentation version: `4.0.0`

**Comment by duncdrum** [comment]
@burki thanks for pointing that out, and yes seems to have been changed in 2010 ouch. @JoernT since you worked on the new user-manager anything to add to Burki's observations?

**Comment by duncdrum** [comment]
I've dealt with the low hanging fruit, but someone with a better grasp of the interface should go over this article. It's very awkward reading, and I can't tell if other parts are outdated beyond what the OP describes

**Comment by burki** [comment]
Thanks - while building my own RPC-client, I noted that the list of methods in the documentation is severly lacking. I will try to come up with a pull request, but this might take a while.

**Comment by duncdrum** [comment]
@burki feel free to add you edits on top of mine in the devguide branch.  The PR would be much appreciated
