### ISSUE TITLE
Screencast for new contributors

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#232]
People report issues to the docs, but sometimes aren't willing to create a PR that solves the issue. I suspect that this could be for 1 of 2 reasons:

1. They are too busy and/or lack the motivation
2. They don't know how to do it with tooling etc (GitHub, Oxygen, PR)

Perhaps we could help resolve (2) with a small video screencast, where we show how to, checkout the docs, create a branch, make an edit to the docs and send a PR.

**Comment by duncdrum** [comment]
While I think that there are other reasons for non-PR reports, I think this is an excellent idea. How do others feel about it?

**Comment by duncdrum** [comment]
Apparently they don't
