### ISSUE TITLE
unrecognized elements warnings 

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#238]
### Where is the problem
E.g. [advanced-installation](http://localhost:8080/exist/apps/doc/advanced-installation)
@eriksiegel These warnings pop up from time to time, I d like to understand where the warning is generated before starting to edit the xml source. 

### What is the problem
some articles contain:
```
*** Unrecognized inline element: XXX
```

### Please provide the following
*   exist-db version: `4.1.0`
*   documentation version: `4.0.1-SNAPSHOT`

**Comment by eriksiegel** [comment]
@duncdrum This is a warning/error that the XSLT that transforms the Docbook into HTML does not recognize a certain element *in a certain mode*.

There are two possible causes:
- You used an element from the Docbook vocabulary that is not supported. See the author reference documentation page for what is in and what isn't
- Or (and that is more likely here) somebody used an inline element in a block context or vice versa. In the original contents, rules for what is inline and what is block were not followed. So for instance a list was started smack in the middle of a paragraph. The current XSLT is very strict on following these rules and will not, for instance, recognize an `<itemizedlist>` when processing inline text. Nor will it recognize an `<emphasize>` when processing block level.

The error message (of which you gave an example) tries to help you. It gives you the mode (in the example: inline) and the element that was not recognized.  In the rendering, it pops up somewhere near where the offensive element was used. 

I hope this helps. If not let me know. Anyway, clicking the link you provided above shows a page without error messages?

**Comment by duncdrum** [comment]
@eriksiegel yes the message is quite clear and helpful. To see the problem, you need to checkout the the latest source build. 
From an architectural standpoint I think we should include this kind of check in our CI or build procedure. But I found the [source](https://github.com/eXist-db/documentation/blob/d0d83730a116e0469ef2ad9c7a7298c8b6ab3418/src/main/xar-resources/modules/xsl/convert-db5.xsl#L219) now.

**Comment by duncdrum** [comment]
@adamretter i can see different options here. I do like the idea that people get a warning in the html view if this is how they edit the contents, so i m inclined to keep the xsl around. 
However, I really think that the same kind of style checking should either be performed on travis or when building for editors who work with bare xml. 
Any preference on where and how to hook this up?

**Comment by duncdrum** [comment]
@adamretter yes from what I can tell, we could of course do the same as XQuery test.

**Comment by duncdrum** [comment]
Ok digging a bit further, just running the xsl via the maven-xml-plugin will not generate the required output. This would need to be run as a kind of integration test for that to  work. 

This leaves us with these options:
*   Create an xqsuite test that duplicates the checks from the xsl
*   add an integration test, and check the rendered html of every article for style warnings
*   modify the schema-files so that the style errors will pop up during validation

**Comment by adamretter** [comment]
Which do you want to do? I don't vote for (1). How about:

4. We run the XSL over the file in some sort of strict mode which fails on a warning.

**Comment by duncdrum** [comment]
@adamretter honestly i feel this is all a bit convoluted. Leave the xsl be and let it do its html rendering, url-checking, etc. as it does now. If there is a quick and easy way to isolate the style checks from everything else, and make them run in a bare bones fashion I don't see it. 

if we don't support db5 element `x` we should exclude it from our schema. No point asking people to validate, to then in the browser tell them `oops...`. 

As for adding an integration test on travis that installs the app and then maybe later runs some headless browser test, i m all for that. But not as the primary means to check for db5 errors. There are other things I much rather test with a headless browser, like search, navbar, etc.

**Comment by adamretter** [comment]
Okay so you want to do (3)?

**Comment by duncdrum** [comment]
yes

**Comment by duncdrum** [comment]
we'll track this as part of #262
