### ISSUE TITLE
[upgrading.xml] Add upgrading instructions for installations from source.

### ISSUE THREAD

**Issue by lguariento** [eXist-db/documentation#250]
It would be useful to add instructions about how to update/upgrade eXist-db for people who installed eXist-db via `git clone git://github.com/eXist-db/exist.git`.

Add a section titled something like _Installing and Upgrading from Source_ with the following instructions.

> In the folder where you installed eXist-db, run `git status` to see which files differ from the updated repository on GitHub. In particular, you're interested to see which are the configuration files you edited and which you want to preserve (e.g. `conf.xml`, `webapp/WEB-INF/controller-config.xml`, `tools/jetty/webapps/exist-webapp-context.xml`, etc.).
> 
> 1. Create a full backup from eXist-db (i.e. to a set of files or .zip file).
> 2. Stop eXist-db
> 3. Make a backup copy of the `webapp/WEB-INF/data directory` directory and any other configuration file you wish to preserve (see above), plus the 'local.build.properties' file in case you edited `build.properties`.
> 4. Run `git checkout -- lib/` to unsign the jar files.
> 5. Run `git status`: you should see no lib/ paths in the output.
> 6. Run `git fetch`.
> 7. Run `git stash`.
> 8. Run `git rebase origin/master` or `develop`, whichever you want.
> 9. Run `git stash pop`.
> 10. Run `./build.sh clean`.
> 11. Run `./build.sh jnlp-unsign-all all jnlp-sign-exist jnlp-sign-core jnlp-sign-exist-extensions`.
> 12. Copy back the configuration files (and, optionally, the' local.build.properties` - see above).
> 12. Start your eXist-db and you should now have an up-to-date eXist-db instance running.

**Comment by duncdrum** [comment]
yes this could go with the upgrading instructions, can you prepare a Pull Request?
