### ISSUE TITLE
[advanced-installation.xml] Instructions for installing eXist-db via git clone

### ISSUE THREAD

**Issue by lguariento** [eXist-db/documentation#251]
I don't seem to find instructions, in the documentation, about how to install eXist-db via git clone. Is it buried somewhere, or has it been taken out by choice? If we add instructions on how to upgrade (see #250), then it migt be consistent to add instructions about how to install.

**Comment by duncdrum** [comment]
the instruction for how to build from source are traditionally with the source code, for exist that means they are [here](https://github.com/eXist-db/exist/blob/develop/BUILD.md). Instead of duplicating this information I d rather add a dynamic link from the docs to the file linked above.

**Comment by lguariento** [comment]
Agree, as long as they're somehow mentioned in the 'installation methods', given that all others installation methods are in the documentation.

**Comment by duncdrum** [comment]
@lguariento turns out that we do have a section in [the docs](http://www.exist-db.org/exist/apps/doc/exist-building.xml)
If you think that something is missing there, just open a new issue or better yet PR.
