### ISSUE TITLE
XQSuite outdated functions in code for suite.xql

### ISSUE THREAD

**Issue by MRodz** [eXist-db/documentation#257]
On http://exist-db.org/exist/apps/doc/xqsuite the provided example seems to be outdated in the code for `suite.xql`. 

The function call

`test:suite(
    inspect:module-functions(xs:anyURI("math.xql"))
)`

has 0 results when tested in exist-db 4.2.0 and 4.1.0, while [Joe's approach](https://gist.github.com/joewiz/fa32be80749a69fcb8da) with `util:list-functions` instead of `inspect:module-functions` yields the expected testsuite outcome.

*   exist-db version: `4.2.0`
*   documentation version: current website

**Comment by duncdrum** [comment]
ok did some preliminary digging, it appears or unit tests of the test suite inspect function are currently being skipped. Unless someone has a good reason for why they should be skipped I m moving this to the main repo.
/move eXist-db/exist
