### ISSUE TITLE
Fix the naming of XQuery files

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#258]
As per the "Preface" page `xiii` of the O'Reilly eXist Book, we should use the agreed file naming conventions for XQuery Main Modules and XQuery Library Modules.

Reproduced here:

## XQuery Module Types:

* XQuery main module
    A main module is defined as having a query body. Simply put, this means that an XQuery processor can directly evaluate the XQuery code in this file.

* XQuery library module
    A library module does not have a query body and must start with a module declaration. Again, simply put, this means that an XQuery processor cannot directly evaluate a library module; rather,  the library module must be directly or indirectly imported into a main module.

## XQuery file naming conventions:

* `.xq`
The `.xq` filename extension is to be used for all main modules.

* `.xqm`
    The `.xqm` extension is to be used for all library modules. The `m` suffix in the file extension indicates that the XQuery module starts with a module declaration and is therefore a library module.

**Comment by joewiz** [comment]
Here, here!

For context, see https://exist-open.markmail.org/thread/aanuki7uwfdrg4hp.

**Comment by duncdrum** [comment]
🤷‍♂️ Many of the file names in the docs are taken straight from exist-db apps, so unless we do this org wide it we'll end up with something inconsistent. fixing xquery naming convention across exist-db.org seems a lot of work for little gain, unless I'm missing something here. I m happy to be stricter in enforcing this for new contributions, but as for backwards fixes this is on the lower end of my prioriies pile.
