### ISSUE TITLE
[production_web_proxying] add note about client_max_body_size to nginx 

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#264]
### Where is the problem
By default nginx has `client_max_body_size 1m;`

### What is the problem
not allowing larger sizes interfers with uploading .xar packages from development systems.
needs to be set twice in `nginx.conf` in `http` and `server` under `location`

### Please provide the following
*   exist-db version: `4.3.0`
*   documentation version: `4.0.3`

**Comment by duncdrum** [comment]
@martindholmes looks like Apache has a similar problem [tei-list](https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1810&L=TEI-L&P=47378)

**Comment by martindholmes** [comment]
@duncdrum If I understand the documentation correctly (https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody) the default in Apache is unlimited, but it's unlikely a cautious sysop would leave it that way.

**Comment by dizzzz** [comment]
should this really be documented in eXist-db documentation? probably not, only in 'generic terms' like

 "your reverse proxy might have a limit on your HTTP request body, size URL etc. As a consequence it might nog be possible to upload large documents to eXist-db. Please consult the documentation for you reverse proxy for details." 

Nothing more....

**Comment by duncdrum** [comment]
@dizzzz yes generic terms is what i had in mind with adding a note. but looking at the number of users (un-) knowingly struggling with this and blaming exist-db's storage capacities I think we should mention something in our docs.
