### ISSUE TITLE
[xquery.xml] exist-serialization PI is undocumented

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#265]
I found a mailing list post (signposted by @joewiz) where @shabanovd and @wolfgangmm mention a Processing Instruction, which as far as I know isn't commonly known. It's purpose appears to be for controlling the serialization of XML documents. I also could not find any reference to this in the eXist-db documentation. This should be documented

Perhaps @joewiz also knows about this?

Some scant details are in the mailing list posts from Dmitriy and Wolfgang here:
http://markmail.org/message/w4g4kt3o4gh5dvy6

**Comment by duncdrum** [comment]
Looking through the existing documentation about [serialization parameters](http://www.exist-db.org/exist/apps/doc/xquery.xml?field=all&id=D3.49#serialization).  I m starting to wonder if the whole article shouldn't be broken into multiple articles.

**Comment by duncdrum** [comment]
more-information needed will keep triggering the bot

**Comment by duncdrum** [comment]
that being said @wolfgangmm @joewiz @shabanovd its been 14 days a life-sign please.

**Comment by joewiz** [comment]
Here's what I have pieced together: In [the exist-open thread](https://markmail.org/message/w4g4kt3o4gh5dvy6) mentioned in @adamretter's original post above, @wolfgangmm wrote:

> Based on Dmitryi's recent additions to trunk, you could thus add a pi to your 
document:
> 
> ```xml
> <?exist-serialize indent="no" output-doctype="yes"?>
> ```
> 
> Unfortunately I could not test this feature in combination with WebDAV yet.

Also, digging through source, @shabanovd added this feature in https://github.com/eXist-db/exist/commit/0cda7b6387aa4fb8ff82e6bb14a4de81bb210f74 with the following commit message:

> [feature] use <?exist-serialize?> as properties container for serializer. It will affect all interfaces and rewrite settings passed to serializer.

This code is still in source, basically unchanged (see https://github.com/eXist-db/exist/blame/3d5ceea8762702b74209836f58cbc5c0d00f1211/src/org/exist/storage/serializers/Serializer.java#L459). However, there are no tests (I assume it worked as described, but without test, who knows if it still works?) and, indeed, no documentation.

@shabanovd Would you be able to submit tests for this feature to demonstrate that it still works? Also, is there anything you would add to the information I've pasted in here that we should include in the documentation?

**Comment by adamretter** [comment]
@joewiz I have just tried to use this facility, and I have been unable to trigger the code that uses it. It seems that it is only used by some parts of eXist-db under some conditions and is not generally applicable.

May I now suggest that we simply create a PR to remove this code, and have that close this ticket...

**Comment by joewiz** [comment]
@adamretter Wow, thanks for this research. Your plan to create a PR to remove this code and sounds good to me.
