### ISSUE TITLE
Package not accessible via public-repo by "doc" abbrev

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#269]
### Where is the problem

In the generated package's expath-pkg.xml file.

### What is the problem

The same issue I fixed in https://github.com/eXist-db/shared-resources/pull/37 affects the documentation app. Its `@abbrev` (in `expath-pkg.xml` under `package/@abbrev`) used to be "doc", but it is now "exist-documentation".

As a result, the build step during which xars are fetched for the autodeploy directory (https://github.com/eXist-db/exist/blob/develop/build.properties#L33), or calling `./build.sh download-xars` (https://github.com/eXist-db/exist/blob/develop/installer/apps.properties#L2), will fail to download the documentation app. Here's the relevant portion of the log from `./build.sh download-xars`:

```
download-xar:
    [fetch] Getting: http://demo.exist-db.org/exist/apps/public-repo/pkg.zip?abbrev=doc&zip=yes&processor=4.5.0-SNAPSHOT
    [fetch] To: /var/folders/ky/gdx8y19x3gj7xxjm1zr3wr_r0000gn/T/FetchTask8738793445563451693tmp
    [fetch] Error opening connection java.io.FileNotFoundException: http://demo.exist-db.org/exist/apps/public-repo/pkg.zip?abbrev=doc&zip=yes&processor=4.5.0-SNAPSHOT
    [fetch] Can't get http://demo.exist-db.org/exist/apps/public-repo/pkg.zip?abbrev=doc&zip=yes&processor=4.5.0-SNAPSHOT to /var/folders/ky/gdx8y19x3gj7xxjm1zr3wr_r0000gn/T/FetchTask8738793445563451693tmp
```

The public repo responds to this request by build script with a 404 error and `<p>Package file not found!</p>`. 

Unfortunately I'm not sure how we should address this in the mavenized build process now used for the documentation app... But you might see how I distinguished between the package "app" name and "abbrev" name in `build.properties`, `build.xml`, and `expath-pkg.xml.tmpl` in my PR that fixed this (again) in the shared-resources app: https://github.com/eXist-db/shared-resources/pull/37/files.

### Please provide the following

*   exist-db version: `4.x.x-develop`
*   documentation version: `4.0.3`

**Comment by duncdrum** [comment]
so to keep this inline with the maven world which might come to exist in the near future, i would suggest fixing `build.sh download-xars` instead of changing the `artifact-id` in  `@abbbrev` 

While, I remember @dizzzz having strong feelings about not wanting the docs on his exist-instance. Given that we haven't fixed the update cycle of exist-db.org and keep trailing I vote to revisit his objections once the exist-db.org update woes have been addressed. 

/move eXist-db/exist
