### ISSUE TITLE
Explain autodeploy directory

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#272]
### Where is the problem

https://exist-db.org/exist/apps/doc/repo
https://exist-db.org/exist/apps/doc/exist-building

### What is the problem

The documentation doesn't discuss the `autodeploy` directory at all (https://exist-db.org/exist/apps/doc/search.html?q=autodeploy) or where the list of apps fetched during the build process is located (`build.properties` -> `autodeploy`; `installer/apps.properties` -> `apps`).

I just noticed this (I've been using the autodeploy directory as a sort of poor man's on-disk package manager for exist) and realized that we should perhaps document this.

### Please provide the following
*   exist-db version: `4.4.0`
*   documentation version: well, the [website](https://exist-db.org/exist/apps/doc/documentation.xml) says "1Q18", but there's no `4.0.3`-like number visible there to reference. I see the current develop branch is at `4.0.4-SNAPSHOT` (if [this](https://github.com/eXist-db/documentation/blob/master/pom.xml#L15) is the right place to look?)

**Comment by duncdrum** [comment]
see 6bd6156008508de9c24981a441bf09c700cc64d1
