### ISSUE TITLE
[diagnostic.html] diagnostic page and nondescript ids

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#285]
### What is the problem
Outgoing and incoming link checks should be part of a unit test. 

We should strive for more descriptive ids (`3.4.1` will change if a new section is added), so we can make sure that not only a target exists, but actually is the correct content. This would make for nicer URLs and easier reference. 

### Please provide the following
*   exist-db version: `4.5.0`
*   documentation version: `4.0.5-SNAPSHOT`

**Comment by adamretter** [comment]
So I think we have to do a few things:

1) Write a script which pulls out all the dewey id's that are currently in use and stores them in a document which maps old ids to new ids.

2) Move to a better id scheme based on shortened names etc.

3) Modify the XSLT to also add in anchors for the old ids.

**Comment by duncdrum** [comment]
1) If i find a good script that catches all the old ids i ll let you know. For now old ids will still work, but new ids have replaced them.
2) New ids are in and in use, more work in that area coming soon with proper schema validation
3) xsl is on its way out, xquery is more performant and easier to maintain.
