### ISSUE TITLE
backup.xml: Missing information about a configuration aspect

### ISSUE THREAD

**Issue by funkyfuture** [eXist-db/documentation#308]
### What is the problem

In the section "Triggering backups using the Dashboard" the following is stated:

> The default storage directory is webapp/WEB-INF/data/export/. You can configure a different directory in the configuration file conf.xml.

But neither does this documentation nor the one that covers configuration or the shipped `conf.xml` contain any information what configuration key would be used to define that "different directory". or it is hard to find.

### Please provide the following
*   documentation version: fetched on March 1st 2019

**Comment by duncdrum** [comment]
I guess a code-listing with the conf.xml segment would be an improvement. Could you  open a PR?

**Comment by funkyfuture** [comment]
sure, but i don't have the necessary information.

**Comment by duncdrum** [comment]
se2 #333

**Comment by duncdrum** [comment]
@adamretter i have to agree, if there is such a setting in the `conf.xml` mind pointing it out to me. I can't find it either.

**Comment by duncdrum** [comment]
So the main problem is that the example on `backup.xml` says `<parameter name="output" value="export"/>` but on `configuration.xml` it says `<parameter name="dir" value="backup"/>`
These two code listings should be identical, imv.
