### ISSUE TITLE
"*** Unrecognized inline element: itemizedlist" error.

### ISSUE THREAD

**Issue by lguariento** [eXist-db/documentation#309]
Hello,

line 122 here:

`documentation/src/main/xar-resources/data/advanced-installation/advanced-installation.xml`

throws a `*** Unrecognized inline element: itemizedlist` error (see https://exist-db.org/exist/apps/doc/advanced-installation.xml).

**Comment by duncdrum** [comment]
See #238, this has been fixed in recent releases, but we would need to update exist-dB.org

**Comment by lguariento** [comment]
Ah ok, thanks.
