### ISSUE TITLE
recode site:expand-links()?

### ISSUE THREAD

**Issue by jensopetersen** [eXist-db/documentation#31]
It should be discussed whether or not to recode site:expand-links() on page.html

because they do not work if the documentation app is installed elsewhere than on exist-db.org, and 

because the function needlessly involves searching all collections in db for abbrev attributes.

http://markmail.org/message/5xb6eyikef4oxjcj

The same applies to the other core apps using the same function.

**Comment by duncdrum** [comment]
I know this is ancient history, but I think this is actually bug, the documentation app is indeed installed on all eXist-db instances by default, so we shouldn't have any eXist-db.org specific code in the default package at all. It just creates a bunch of console errors.

**Comment by adamretter** [comment]
@duncdrum @jensopetersen I agree this is a nasty one.

**Comment by duncdrum** [comment]
Issue is now fixed in documentation app
