### ISSUE TITLE
Navigation: Table of Content

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/documentation#33]
There is a lot of documentation for eXist, but navigation is not easy at all.

I'd propose to add a Table of Contents (linked or even embedded-but-collapsed) on each page,  this would be a good improvement.

Maybe... using the FullText/lucene index we'd could think of a generated index, maybe 'tag cloud' displayed.

**Comment by joewiz** [comment]
There is a "Contents" sidebar to the right of the article. Is this not what you had in mind?

**Comment by dizzzz** [comment]
Ah no, I was thinking of a contents table over all documentation pages. I once started to visualize 'titles' and 'subtitles' of several pages, but the structures of quite some documents are inconsistent (article vs ....), and elements are on location where they probably should not be.

In essence all documentation should be refactored into one one type of XML, at least all docbook documents should have the same structure.

**Comment by joewiz** [comment]
Agreed, the variation in the structure is not ideal - and that all documentation refactored into a consistent format (be it XML or markdown). Achieving structural consistency is key for the next stage, but it would only get us so far. Our difficulty in seeing the big picture is a symptom we need to diagnose. Each article is good on its own, but they do not all fit in coherently. We might consider an exercise where we imagine we're starting the documentation over, from scratch. What would the ideal table of contents for eXist's documentation look like?

**Comment by eriksiegel** [comment]
The main documentation landing page now contains links to *all* articles. 
It also holds *2* references to the articles: One by title and one by subject.

IMHO adding a reference to all articles (1Q18 more than 75!) to each page (although it would be easy to do this) would be overdoing things enormously: Too much info on each page....

I suggest we close this one?
