### ISSUE TITLE
Editing: eXide-edit button

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/documentation#34]
To lower the threshold of editing the documentation XML, it might me a nice idea to add a 'edit' button/link to each page, that fires-up exude with that page.

Probably this link should be visible only when logged in as admin or so.

**Comment by joewiz** [comment]
I really like the idea of making it easier to edit the documentation when you spot a problem, but how would these changes be integrated back into source control?

**Comment by wolfgangmm** [comment]
I also had some ideas for redesigning the documentation app: use markdown instead of docbook. tei publisher can basically render github markdown, so we could rely on it for display in a separate app, but at the same time publish everything to github pages as well.

**Comment by adamretter** [comment]
I don't like the idea of using Github pages, the docs should be on the eXist website. We already have too many different locations imho

**Comment by shabanovd** [comment]
+1 for Github pages only

**Comment by wolfgangmm** [comment]
sorry, guys, you're getting it wrong: the documentation would stay in its own app on the website as before. The idea just is to use a format (gfm) which is simpler to edit for people and integrates nicely with github workflow. Bonus: replace custom code required for display, search etc. by standard modules.

**Comment by adamretter** [comment]
@wolfgangmm Now I am confused, above you said this:

> but at the same time publish everything to github pages as well

So you do or don't want to use github pages?

**Comment by adamretter** [comment]
@shabanovd "Github pages" and the "Github wiki" are two very different things

**Comment by wolfgangmm** [comment]
@adamretter sorry, I mixed up things myself. I don't want to use github pages nor github wiki, just switch to markdown instead of docbook as it is faster to write and users could create a pull request directly from within github.

**Comment by shabanovd** [comment]
@adamretter "Github wiki" have "wiki pages" https://help.github.com/articles/about-github-wikis/, so that's why "Github wiki pages"

@wolfgangmm my concern is time to production (and manual documentation server update after PR reviewed and merged)

**Comment by adamretter** [comment]
@shabanovd With the documentation, once a PR is merged what if we had a Jenkins pipeline that built and published a new XAR?

**Comment by adamretter** [comment]
@wolfgangmm Not sure if it is pertinent, but I thought I would mention that the entire eXist O'Reilly book is written in DocBook 4.5.

**Comment by shabanovd** [comment]
@adamretter I'll be have with anything that minimize time to production
