### ISSUE TITLE
[uploading-files.xml] Remove mention of collections browser

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#393]
### Where is the problem

https://exist-db.org/exist/apps/doc/uploading-files has a section, “Uploading files using the Dashboard”. 

### What is the problem

The collections panel has been removed from Dashboard.

### Please provide the following
*   exist-db version: `5.0.0`
*   documentation version: version on exist-db.org

**Comment by duncdrum** [comment]
see #271
