### ISSUE TITLE
[BUG] documentation on exist-db.org is screwed up

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#425]
See - http://www.exist-db.org/exist/apps/doc/configuration

<img width="1413" alt="Screenshot 2020-01-21 at 21 40 19" src="https://user-images.githubusercontent.com/1264057/72841471-bce35f00-3c96-11ea-897c-92ce5ea0a298.png">

1. Note the right-side menu "Contents" is just `element` over and over
2. Sections seem to be missing
3. Term list of "divided into eleven sections" is mangled up.

**Comment by duncdrum** [comment]
problem 1 `spacing="compact"` is on the variable listing, this has bitten us many times, and basically i think we should purge this attribute as it just generates trouble by mixing concerns. CSS does the layout, docbook the contents. Also this would work better as an ordered list, we're already at 13 elements, but claim there to be eleven. 

problem 2 `docbook.xql` returns `/text()` so it skips inline elements such as `<tag>` it shouldn't https://github.com/eXist-db/documentation/blob/189f5fb5b9432b77866eb6b3474ec7590076993c/src/main/xar-resources/modules/docbook.xql#L70
