### ISSUE TITLE
Change log in xar-assembly getting out of hand

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#433]
**Is your feature request related to a problem? Please describe.**
The generated change log is growing out of hand, it’s also missing the last release (my bad). I suggest to keep changes of each major semver run in there but to delete older entries. The full history is available here on GitHub anyways.

**Comment by joewiz** [comment]
Sounds good. I should just note that an app's changelog displayed on the public repo is sourced from the newest version of an app, so removing changelog entries in the newest release will cause those entries to be removed from the public-repo's listing too.

**Comment by joewiz** [comment]
I just realized that the documentation's changelog isn't displayed at all, for some reason. See http://exist-db.org/exist/apps/public-repo/packages/exist-documentation.html?eXist-db-min-version=5.2.0. Compare to https://exist-db.org/exist/apps/public-repo/packages/eXide.html?eXist-db-min-version=4.0.0. This suggests that the maven build not putting the changelog into repo.xml, e.g., https://github.com/eXist-db/eXide/blob/develop/repo.xml#L14-L21.

**Comment by duncdrum** [comment]
@joewiz just checked so the change-log is in `repo.xml` looks like a display problem with public-repo maybe its too long?

see https://github.com/eXist-db/public-repo/issues/50
