### ISSUE TITLE
[scheduler.xml]: Broken link to Quartz Cron Trigger Tutorial

### ISSUE THREAD

**Issue by vincentml** [eXist-db/documentation#456]
In the Scheduler Module documentation at https://exist-db.org/exist/apps/doc/scheduler there is a broken link in the Cron Scheduling section in the text "This section was copied from the Quartz Cron Trigger Tutorial." It look like the new link is http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html

**Comment by adamretter** [comment]
Thanks for reporting @vincentml we will get that fixed.
