### ISSUE TITLE
There is only the master branch in git for documentation

### ISSUE THREAD

**Issue by lcahlander** [eXist-db/documentation#53]
Should we not have a develop branch?

**Comment by adamretter** [comment]
Well this is a much smaller project and so we don't apply the git-flow
develop/master principal here so far.

On 14 February 2015 at 15:17, Loren Cahlander <notifications@github.com>
wrote:

> Should we not have a develop branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eXist-db/documentation/issues/53>.
>



-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Comment by dizzzz** [comment]
indeed....

**Comment by lcahlander** [comment]
ok.  I was just asking. ;)
