### ISSUE TITLE
Update new range index documentation to describe range:matches function

### ISSUE THREAD

**Issue by djbpitt** [eXist-db/documentation#576]
**Is your feature request related to a problem? Please describe.**

The documentation of the new range index at <https://exist-db.org/exist/apps/doc/newrangeindex> says:

> fn:matches is currently not supported due to limitations in Lucene's regular expression handling. If you require fn:matches a lot, consider using the old range index.

There is no mention on this page of the `range:matches()` function. Even with its Lucene-related limitations, this would be an appropriate place to mention its availability, which I learned about only accidentally, when Wolfgang happened to mention it on the exist-open mailing list. See https://exist.markmail.org/search/?q=range%3Amatches#query:range%3Amatches+page:1+mid:uw2qoco4sof7r2bg+state:results.

**Describe the solution you'd like**

Update the aforementioned web page to tell users there about `range:matches()`.

**Describe alternatives you've considered**

I previously followed the current advice on the official documentation page and created old range indexes alongside new ones so that I could use `fn:matches()` with the old range indexes, while being able to take advantage of the new range index for other purposes. Had that advice also mentioned the `range:matches()` alternative, that would have simplified my index development.

**Comment by djbpitt** [comment]
Should this also have a *docs-outdated* label?

**Comment by adamretter** [comment]
Thanks @djbpitt I agree with your assessment and suggestions. Would you be able to send a PR to update the docs please?

**Comment by djbpitt** [comment]
@adamretter Done: https://github.com/eXist-db/documentation/pull/577. Thank you for the quick response!
