### ISSUE TITLE
[devguide_xmldb] Example in documentation does not build

### ISSUE THREAD

**Issue by bakcsa83** [eXist-db/documentation#589]
The java example on [this page](https://exist-db.org/exist/apps/doc/devguide_xmldb) does not work because the following packages do not exist in `xmldb-api:1.7.0`  :
```
import org.xmldb.api.base.*;
import org.xmldb.api.modules.*;
import org.xmldb.api.*;
```
Also, `org.exist.xmldb.EXistResource` is missing from `exist-core:5.0.0`

Could someone point me to an example code that helps me getting started on writing java code for exist-db using the latest core release?

**Comment by duncdrum** [comment]
hello bakcsa83, can you please tell us which version of the docs and which version of exist. Have you checked if there have been updates to the article in later version. You can find the sources here in this repo.

**Comment by adamretter** [comment]
@bakcsa83 I think it is present - https://github.com/eXist-db/exist/blob/eXist-5.0.0/exist-core/src/main/java/org/exist/xmldb/EXistResource.java
