### ISSUE TITLE
Remove  ftlegacy.xml documentation on legacy ft-index

### ISSUE THREAD

**Issue by adamretter** [eXist-db/documentation#61]
This was removed from the code-base in https://github.com/eXist-db/exist/commit/d0c03f19ac8082a0502f4dc817cb94818eea26ea

**Comment by joewiz** [comment]
@adamretter Could you confirm you still want this removed? I recall you saying something about someone who needed the legacy ft index?

**Comment by adamretter** [comment]
Yes please the code is no longer there in 3.0

**Comment by duncdrum** [comment]
indexing.xml contains a code listing mentions legacy-ft index, but I'd consider that unproblematic in the context of showing how to add any index to conf.xml
there is ft-legacy, which can be removed now that we version the documentation app.

**Comment by duncdrum** [comment]
One code listing in indexing.xml still mentions legacy-ft, but I d consider that low priority since it's in the context of how to provide custom indexes.
