### ISSUE TITLE
[BUG] standard linter throws error about one of its dependencies

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#628]
To reproduce

run `standard 'src/test/**/*.js'`  see d98c5010342e9dc99f22915f648ae26f2114ff32
see https://github.com/standard/deglob/issues/20
this should be renabled as part of the npm test command.

It might go away with more updates to dependencies i can't tell

Recording of runs on our old dasboard is working again
![Screenshot 2021-06-07 at 23 59 43](https://user-images.githubusercontent.com/6205362/121092844-7a1f1a00-c7ec-11eb-8b02-09d09d178855.png)

There is now an additional pill on the readme, in addition to the link, so it's easier to find. 

**Context (please always complete the following information):**
- eXist-db Version: [e.g. 5.3.0-SNAPSHOT]
- App Version: [e.g. 5.2.1-SNAPSHOT]

**Comment by line-o** [comment]
standard linter runs locally without an issue.

**Comment by duncdrum** [comment]
i ve tested this with two node and standard versions locally and in all instances consistently reproduced the error we saw on CI. The deglob package is part of the standard org, and standard is its sole user in our repo. I expect there to be a version requirement that triggers, this, some combination of Standard `x` with node `y`. The gulp-standard plugin works without a hitch. 

Its very well possible that once #629 is resolved, the issue will disappear.
