### ISSUE TITLE
[suggestion] bump node to v12

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#629]
Node 10 is EOL, while we are replacing outdated dependencies, we should also use a more current LTS node version, we already have dependency PRs dropping node 10 it ll only get worse

**Comment by line-o** [comment]
I am very much in favour of this update. Is there a reason not to use node 14 right away?

**Comment by line-o** [comment]
The current LTS is 14.17.0 LTS

**Comment by duncdrum** [comment]
nope, if all our deps run on 14 no reason not to long jump
