### ISSUE TITLE
[BUG] `mvn package` should not modify files in the src folder

### ISSUE THREAD

**Issue by line-o** [eXist-db/documentation#633]
**Describe the bug**

after running `mvn package` git shows following files as changed

```
	modified:   src/main/xar-resources/data/extensions/listings/listing-1.xml
	modified:   src/main/xar-resources/data/extensions/listings/listing-2.xml
	modified:   src/main/xar-resources/data/newrangeindex/listings/listing-5.xml
	modified:   src/main/xar-resources/resources/scripts/bootstrap.min.js
	modified:   src/main/xar-resources/resources/scripts/bootstrap.min.js.map
	modified:   src/main/xar-resources/resources/scripts/jquery.slim.min.js
	modified:   src/main/xar-resources/resources/scripts/jquery.slim.min.map
	modified:   src/main/xar-resources/resources/styles/bootstrap.min.css
	modified:   src/main/xar-resources/resources/styles/bootstrap.min.css.map
	modified:   src/main/xar-resources/resources/styles/doc.min.css
	modified:   src/main/xar-resources/resources/styles/exist-2.2.min.css
	modified:   src/main/xar-resources/resources/styles/style.min.css
```

**Expected behavior**

mvn package to leave the src folder untouched

**Comment by adamretter** [comment]
This is what I was talking about on the Community Call last night ;-)

**Comment by line-o** [comment]
Yes, I wanted to have it visible and not to forget about it once I saw it myself.

**Comment by line-o** [comment]
As @duncdrum already mentioned the output paths in the Gulpfile.js need to change to a folder not in version control (see https://github.com/eXist-db/documentation/blob/77daa1d50ea54a50fc48d64dfb07d0cf292965a2/Gulpfile.js#L23 and following).

For this to work the maven steps that follow must pick up the files at their new location.

**Comment by line-o** [comment]
Especially true for minified scripts and styles.
We should discuss if we want to keep the formatted XML files in version control  (anything matching `src/main/xar-resources/data/**/*.xml`).

**Comment by duncdrum** [comment]
i have put the minified and their `.map`s  on `.gitignore` as i needed to update it anyway. I would keep the listings and data files in VCS as this is 99% of what updating and reviewing the docs is all about. 

the necessary steps are indeed having gulp output into a new directors, and then `kuberam-expath` pick them up from there, as it is the last step.
