### ISSUE TITLE
[xquery.xml]: Remove fn:document-uri#0 from list of unimplemented functions

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#654]
**Describe the problem**

The `fn:document-uri#0` is implemented (thanks to @dizzzz's https://github.com/eXist-db/exist/pull/3644), but this function is still listed as unimplemented in https://github.com/eXist-db/documentation/blob/master/src/main/xar-resources/data/xquery/xquery.xml#L111-L149.

**Screenshots**

n/a

### Please provide the following
*   exist-db version: `5.3.0-SNAPSHOT`
*   documentation version: current develop

**Comment by joewiz** [comment]
And [as pointed out](https://github.com/eXist-db/documentation/issues/742#issuecomment-1064491157) by @PieterLamers so is `map:merge#2`.

**Comment by duncdrum** [comment]
docs are current as of v6
