### ISSUE TITLE
Problems on overwriting 2.2 with 3.0 RC

### ISSUE THREAD

**Issue by jamescummings** [eXist-db/documentation#69]
(Issue with solution provided)

I just wanted to note that documentation (which I probably didn't read anyway, oops) should instruct you to remove existing 2.2 or other previous exist before installing 3.0.  The installer asks if you want to overwrite the files, but even if you say yes, it _doesn't_ overwrite certain files. I had to update my java to 1.8 to run the 3.0 installer. The problem then emerges of it trying to use the wrong version of java to run the files even though you have installed with the correct version.
e.g. bin/startup.sh will remain pointing to the previous java version resulting in:
"Exception in thread "main" java.lang.UnsupportedClassVersionError: org/exist/start/Main : Unsupported major.minor version 52.0" as a problem.

Even if you run the startup.sh then having changed it to point to the right Java, other files give you problems. e.g. 
"java.lang.NoClassDefFoundError: com/github/krukow/clj_lang/ITransientCollection"
or 
" err:XPST0081 error found while loading module restxq: Error while loading module modules/restxq.xql: No namespace defined for prefix text [at line 271, column 40]" if trying to go to the dashboard.

Solution:

sudo rm -rf /usr/local/eXist-db/ 

then make sure you are running the right version of java with:
java -version

then run the installer for 3.0RC again.

**Comment by joewiz** [comment]
Fixed by #87. Thanks @jamescummings and @duncdrum!
