### ISSUE TITLE
Prepare v5.4.0 release

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#742]
With these new releases of eXist, we should issue new corresponding versions of the documentation app. 

(Thanks to @wolfgangmm, the exist-db.org server is now running eXist 5.3.0, and I have updated the version of the documentation app there accordingly.)

**Comment by joewiz** [comment]
(Sorry @duncdrum for the errant assignment & label. I started the issue via the bug report template but forgot to clear those fields before submitting.)

**Comment by joewiz** [comment]
I just published documentation v5.4.0. Post mortem:

- Initially `mvn -DdryRun=true release:prepare` was failing, and examining the docker logs revealed that my local image of `existdb:existdb` was stale, and the package wouldn't install on the older version of eXist in docker. The build process itself doesn't fetch `:latest`. I had to manually run `docker pull existdb/existdb:latest`. Then the dry run succeeded.
- The github-release-plugin did a great job of uploading the .xar to GitHub Releases. It also uploaded a .jar version too - odd - so I deleted it from the Releases page. I also had to manually insert the release notes from xar-assembly.xml into the Releases page. (Though I didn't use mvn:site to prepare release notes - I noticed this too late, after I'd already prepared the release notes by hand.)
- The build generates an uncommitted artifact: 
    > <img width="526" alt="Screen Shot 2022-02-04 at 9 37 42 AM" src="https://user-images.githubusercontent.com/59118/152547453-5bad09e3-08d4-4105-8136-f7940bc4279a.png">
    This doesn't appear to be right - as significant whitespace has been inserted into a source file.
- Also, the build generates uncommitted package.json and package-lock.json files. Shouldn't these be committed with the release?

**Comment by joewiz** [comment]
@PieterLamers I linked to the file in question in https://github.com/eXist-db/documentation/issues/654. If you're so inclined, I'd certainly welcome a PR! :-)

**Comment by adamretter** [comment]
@joewiz Should we close this issue?
