### ISSUE TITLE
Document use of util:expand on attributes

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#75]
See feature added in https://github.com/eXist-db/exist/pull/1130.

This should probably go into http://exist-db.org/exist/apps/doc/xquery.xml#serialization

> `highlight-matches= both | elements | attributes | none`
> when querying text with the full text or n-gram extensions, the query engine tracks the exact position of all matches inside text content. The serializer can later use this information to mark those matches by wrapping them into an element `<exist:match>`.
> Setting `highlight-matches=both` will enable this feature for every kind of indexable node.

`util:expand()` is also covered in http://exist-db.org/exist/apps/doc/kwic.xml, but I'm not sure the kwic module itself knows how to deal with matches on attributes.

The Lucene article at http://exist-db.org/exist/apps/doc/lucene.xml mentions `<exist:match>`:

> Or you can ask eXist-db to highlight each match with an exist:match tag, which you can later use to locate the matches within the text.

I seem to recall that the new range index highlights matches, but this is not covered in http://exist-db.org/exist/apps/doc/newrangeindex.xml.

**Comment by ljo** [comment]
@joewiz Thanks for the summary. I will also test this with the new kwic2j app (reimplementation of kwic module).

**Comment by duncdrum** [comment]
@joe looks to me as if this should go into `util.xml`

**Comment by adamretter** [comment]
@ljo What is kwic2j and where is it? We had someone (Rachul Gupta) asking for help with the Kwic module on the mailing list recently...

**Comment by adamretter** [comment]
@duncdrum Sorry which feature did I contribute?

**Comment by duncdrum** [comment]
@adamretter https://github.com/eXist-db/exist/pull/1130

**Comment by duncdrum** [comment]
closing as i can no longer reconstruct what needs to be done here.
@joewiz if there still is an issue please open a new ticket, thx.
