### ISSUE TITLE
Add citations to Retter & Siegel's eXist-db book

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#76]
E.g., to the "Learning XQuery and eXist-db" article at http://exist-db.org/exist/apps/doc/learning-xquery.xml. (Walmsley is listed.)

**Comment by joewiz** [comment]
If not to the main landing page of the documentation app!

**Comment by duncdrum** [comment]
the book is prominently mentioned in getting-help.xml, since it really isn't a learn xquery resource i'd say this makes sense. 
As for the cross-links I agree, more links between the two would be a good idea

**Comment by eriksiegel** [comment]
Book is now also reffed from the main landing page (in the getting started section). Can be closed
