### ISSUE TITLE
Remove XACML documentation

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#77]
See http://exist-db.org/exist/apps/doc/xacml.xml. 

XACML was removed from eXist in https://github.com/eXist-db/exist/pull/996.

**Comment by dizzzz** [comment]
there are no references to this document? I recall I added a query script to check this....

**Comment by joewiz** [comment]
It is listed on http://exist-db.org/exist/apps/doc/documentation.xml. (Search for "xacml".)

Is your idea to keep the document, just not link it to anywhere?

**Comment by dizzzz** [comment]
AH no, we should remove it.

http://exist-db.org/exist/apps/doc/diagnostics.html

**Comment by duncdrum** [comment]
good to delete [this](https://github.com/eXist-db/documentation/blob/master/data/deployment.xml#L476)?
