### ISSUE TITLE
Link to eXist-db Javadocs broken

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#81]
At http://exist-db.org/exist/apps/doc/api/index.html, the first paragraph ends with this sentence:

> For more information, refer to the [Javadocs for this API](http://exist-db.org/exist/apps/doc/api/index.html).

That link leads to:

> HTTP ERROR 404
> 
> Problem accessing /exist/apps/doc/api/index.html. Reason:
>
> Document /db/apps/doc/api/index.html not found

**Comment by joewiz** [comment]
Looks like the link target should be: 

http://exist-db.org/api/

I'm not familiar with this service / URL space though.

**Comment by dizzzz** [comment]
you are right ; this is actually quite an old link.....

**Comment by joewiz** [comment]
Are javadocs still browsable anywhere on exist-db.org or on local builds?

**Comment by adamretter** [comment]
@dizzzz @joewiz I didn't know we even had that. Perhaps @wolfgangmm or @ljo could comment.

In future, if we did the Maven move, we could get rid of the above because the javadocs would be available on Maven Central.

**Comment by dizzzz** [comment]
@adamretter the usecase is different: this is about using a browser to read it online, not in an IDE.

I'll check tonight, I think I remember the location. @joewiz  if you run build.sh javadocs the html files are generated

**Comment by joewiz** [comment]
Do you intend it to restore the javadocs at exist-db.org (in which case we'd keep the link), or is this really just expected to be available locally as an option for developers who care to generate them (in which case we'd mention that those who want javadocs can do A, B, C to get them and access them at URL _)?

**Comment by dizzzz** [comment]
I have no preference :-)

in a way, having this online makes little sense, though it gives regularly hits with google :-) #visibility

**Comment by joewiz** [comment]
Ok, hopefully @wolfgangmm or @ljo will weigh in on their preferences for this.

**Comment by joewiz** [comment]
Closed by #126.
