### ISSUE TITLE
lucene.xml misses info about  Lucene diacritics=yes/no option

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#83]
See http://markmail.org/message/mqladaa6ey2s73b5

**Comment by joewiz** [comment]
Missing from http://exist-db.org/exist/apps/doc/lucene.xml.

**Comment by duncdrum** [comment]
@wolfgangmm if this is still available to users, would you mind either adding a new PR or push another change to the open Facets PR closing this issue. thx
