### ISSUE TITLE
exist-db page still points to old documentation files

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#84]
for example [eXist](http://exist-db.org/exist/apps/doc/advanced-installation.xml#headless)
still mentions 
```sudo tools/wrapper/bin/exist.sh install```

[eXist-db/documentation](https://github.com/eXist-db/documentation/blob/master/data/advanced-installation.xml) contains the current (v3.0) info for 
```tools/yajsw/bin/installDaemon.sh```

**Comment by wolfgangmm** [comment]
Ok, thanks for noticing. I updated the documentation on the server to the latest version.
