### ISSUE TITLE
add new label "needs update"

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#92]
### Problem
When venturing beyond the basic how-to's of exist-db many competing sources of documentation are available. Case in point the xqdoc.xml competes with Adam's book p. 127f, and a post by [Wolfgang](http://xqdoc.org/qs_exist.html) from 2007. 
### Solution
Having a central place with easy means for users to flag information in need of updates might help everyone to more efficiently arrive at the most recent and applicable documentation.

**Comment by duncdrum** [comment]
@shabanovd the former. Not everybody discovering that the documentation is out of sync, can provide the PR to update it. The label should be a flag to help to triage issues more efficiently. How about "outdated" instead?

**Comment by joewiz** [comment]
I've created a new "docs-outdated" label https://github.com/eXist-db/documentation/labels/docs-outdated. Feel free to propose issues where this is appropriate.

@duncdrum Could you please capture the example above in an issue if it isn't already?
