### ISSUE TITLE
[BUG] URL rewrite article validation errors

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/documentation#928]
the URL rewrite article contains multiple instances 
of text literal programlistings

```
<programlisting language="xml">&lt;dispatch xmlns="http://exist.sourceforge.net/NS/exist"&gt;
  &lt;forward url="{$exist:controller}/modules/transform.xq"&gt;
    &lt;add-parameter name="doc" value="{$exist:resource}.xml"/&gt;
  &lt;/forward&gt;
&lt;/dispatch&gt;</programlisting>
```

The test suite rightfully flags those:

https://github.com/eXist-db/documentation/blob/06ef4fb174cae06ca49b97555842792a0d5483da/src/main/xar-resources/modules/test-suite.xql#L137-L157

why was #872 merged despite the test failures

**Comment by joewiz** [comment]
Mea culpa! I'm not sure why I missed the error. I'll submit a PR fixing this.
