### ISSUE TITLE
production_good_practice.xml, web.xml  improve info on disabling REST interface and _query parameter, 

### ISSUE THREAD

**Issue by joewiz** [eXist-db/documentation#98]
As discussed on TEI-L (https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1703&L=TEI-L&D=0&P=21706), many users are unaware that eXist's REST interface includes the ability to submit arbitrary queries. Locking this down on public servers should be documented in the prose documentation, probably http://exist-db.org/exist/apps/doc/production_good_practice.xml#D2.2.5.5. Currently you have to know to dig into web.xml at https://github.com/eXist-db/exist/blob/develop/webapp/WEB-INF/web.xml.tmpl#L87-L101 - or have access to Retter & Siegel chapter 8.

**Comment by simar0at** [comment]
My addition here is: It's not a REST issue if you can do this everywhere within /exist/apps/... To me apps always was NOT REST.

**Comment by joewiz** [comment]
@simar0at You're correct that merely blocking access to `/rest` URLs is insufficient to prevent users from using the eXist REST interface's `_query` parameter. The `_query` parameter can be called even from other controller roots like `/apps`... that is, **unless** eXist's REST interface configuration in `web.xml` is changed from `hidden=false` to `hidden=true`.

**Comment by joewiz** [comment]
Also, as @shabanovd noted in HipChat, controller roots like `/apps` are protected from the `_query` parameter if they have a `controller.xql` at the relevant level of the collection tree - which overrides the default behaviors of the REST interface. After all, the primary purpose of the `/apps` URL space is to enable controller.xql-based URL rewriting. As @adamretter also noted on HipChat, without a controller.xql file, "/apps is just a masquerade of /rest/db/apps."

**Comment by rvdb** [comment]
+1 for adding this to the documentation. And maybe some clarification on _how_ to expose such hidden URLs to the outside world via URL rewriting, as well. After having set the `hidden=true` setting in `web.xml`, I was assuming this controller pipeline should work:

    if (matches($exist:path, '^/controlrest/')) then
      <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="{$exist:root}/servlet/db/apps/"/>
      </dispatch>

...but it doesn't: while the `controller.xql` seems to correctly map and forward the path to the REST servlet,  the operation still is forbidden (suppose I have stored this controller in a `test` app which I am accessing via the URL http://localhost:8080/exist/apps/test/controlrest/):

    HTTP Status 403 -
    type Status report
    message
    description Access to the specified resource has been forbidden.

Or is this not what is meant by "expose defined URLs to the outside world via URL rewriting"?

**Comment by adamretter** [comment]
Taken from Mathias Göbel, if you are using Apache you might want to:

```
RewriteEngine on
RewriteCond %{QUERY_STRING} _query=
RewriteRule (.*) $1? [R=permanent]
```

**Comment by adamretter** [comment]
If you are using NGINX then the equivalent could be something like this:

```
server {
  #... common definitions such as server, root

  location / {
    error_page 999 = @queryinline;

    if ( $query_string ~ "_query=" ) { return 999; }

    # do the remaining stuff
  }

  location @queryinline {
    # do stuff when queryinline matches
    rewrite ^(.*) http://www.your-website.com$1 permanent;
  }
}
```

**Comment by rvdb** [comment]
@adamretter, the Apache snippet could be refined a bit, IMO. When a `_query` request parameter is matched by the rewrite rule you've quoted from Mathias, this will redirect to a new URL with _all_ request parameters removed: http://localhost:8080/exist/apps/?_query='eval=evil'&this-parameter=useful will be stripped to http://localhost:8080/exist/apps/.

If you only want to filter out the `_query` request parameter while retaining all others, this will do:

    RewriteCond %{QUERY_STRING}  (.*)(?:^|&)_query=(?:[^&]*)((?:&|$).*)
    RewriteCond %1%2 (^|&)([^&].*|$)
    RewriteRule ^(.*)$ $1?%2 [R=permanent]

**Comment by adamretter** [comment]
@rvdb Okay thanks Ron
